### ISSUE TITLE
Problem with package

### ISSUE THREAD

**Issue by Visual-Studio-Coder** [louis1001/layer-explosion#3]
parallaxTouchGesture' is inaccessible due to 'internal' protection level.

**Comment by louis1001** [comment]
Leaving a comment to remind myself I have to fix this. Wild that I didn't check before publishing.
Thanks!

**Comment by louis1001** [comment]
I think @novocodev worked on this on their own fork. If that's the case, would you like to make a Pull Request?

**Comment by Visual-Studio-Coder** [comment]
No

**Comment by louis1001** [comment]
Fixed! Please let me know if you get to try it.
